#########################################################################################
# Gevako RS6
# Firmware version 1.4.1
# This firmware version is suitable for the Gevako RS6 with hardware version V1.0.0 - V1.2.0
#########################################################################################

#########################################################################################
esphome:
  name: gevako-rs6-c3
  friendly_name: Gevako RS6-C3
  name_add_mac_suffix: true

  project:
    name: "Gevako.Gevako RS6 Firmware"
    version: "1.4.1"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
#  encryption:
#    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="  # Create your own key in case you like to use api encryption. Use "NEW DEVICE" > "New Device Setup" to create a new key. Key shoud have 43 characters + "=".

ota:
  - platform: esphome
    password: "gevako-ota"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails.
  ap:
    ssid: "Gevako-RS6 Fallback Hotspot"
    #password: "password"

captive_portal:

# Web Server configuration.
web_server:
  port: 80
  version: 3
  #auth:
    #username: "gevako"
    #password: "password"

# Sensors for wifi strength.
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

# Sensors for uptime.
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

# Binary sensor for power source detection.
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT
    name: "Power Source IO"
    id: power_source_state
    internal: true

# Text Sensor for power source.
text_sensor:
  - platform: template
    name: "Power Source"
    lambda: |-
      if (id(power_source_state).state) {
        return {"230 VAC"};
      } else {
        return {"5 VDC (USB-C)"};
      }
    update_interval: 10s

# Switches for the outputs.
switch:
  - platform: gpio
    pin: GPIO0
    name: "Output 1"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.  

  - platform: gpio
    pin: GPIO1
    name: "Output 2"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.

  - platform: gpio
    pin: GPIO3
    name: "Output 3"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.

  - platform: gpio
    pin: GPIO4
    name: "Output 4"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.

  - platform: gpio
    pin: GPIO5
    name: "Output 5"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.

  - platform: gpio
    pin: GPIO6
    name: "Output 6"
    restore_mode: ALWAYS_OFF  #Other options: "RESTORE_DEFAULT_OFF", "RESTORE_DEFAULT_ON", "ALWAYS_ON" or DISABLED.

# Green LED for connection status.
output:
  - platform: gpio
    pin: GPIO7
    id: "green_led_output"

# Green LED for connection status.
light:
  - platform: binary
    name: "Green LED"
    output: green_led_output
    id: green_led
    internal: true

# Software reboot button.
button:
  - platform: restart
    name: "Reboot"

# Check for connection status. Controls green LED.
interval:
  - interval: 1s
    then:
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - light.toggle: green_led
          else:
            - light.turn_on: green_led
#########################################################################################